### ISSUE TITLE
floats with big exponents in absolute value hang factor

### ISSUE THREAD

**Issue by jonenst** [slavapestov/factor#1356] opened 2015-06-11 18:36 UTC
If you type 123e-10000 in the listener, it hangs. It's the same for calling string>number on "123e-10000".
So basically untrusted input can crash factor if number>string is called on it.

This is because we call "/f" on really really big bignums, only to find out that the result is 0.0 or 1/0.

In python (see _Py_dg_strtod from https://github.com/python/cpython/blob/master/Python/dtoa.c) they check an approximation of a "normalized" (ie taking signficant digits into account) exponent against known overflow/underflow values (DBL_MAX_10_EXP and "1 << n_bigtens") around lines 1800.

So in the simplest form, something like this would fix the problems (this keeps the /f to numbers that work in sub milliseconds times).
```diff
diff --git a/core/math/parser/parser.factor b/core/math/parser/parser.factor
index da157e9..21c501b 100644
--- a/core/math/parser/parser.factor
+++ b/core/math/parser/parser.factor
@@ -67,7 +67,11 @@ TUPLE: float-parse
     [ [ inc-point ] 4dip ] dip add-digit ; inline
 
 : make-float-dec-exponent ( float-parse n/f -- float/f )
-    [ [ radix>> ] [ point>> ] [ exponent>> ] tri - (pow) ] [ swap /f ] bi* ; inline
+    {
+      { [ over exponent>> 1000 > ] [ nip 1/0. * ] }
+      { [ over exponent>> -1000 < ] [ nip 0.0 * ] }
+      [ [ [ radix>> ] [ point>> ] [ exponent>> ] tri - (pow) ] [ swap /f ] bi* ]
+    } cond ; inline
 
 : make-float-bin-exponent ( float-parse n/f -- float/f )
     [ drop [ radix>> ] [ point>> ] bi (pow) ]
```

I don't mean for this patch to be applied as is because it ignores the "point"  and the significant digits (so it's incorrect for strings like "100000[snip a thousand zeros]0000000e-1001" and also using 1000 as a limit is pretty arbitrary (they use smaller limits in python but it's more complicated..). 64bit IEE754 have 10^-310 to 10^310 range so maybe just plain 512 is enough ? Also it's needed for make-float-bin-exponent.
What do you think ?

**Comment by mrjbq7** [comment] 2015-06-11 19:27
See #1231 (maybe a duplicate of that).

**Comment by jonenst** [comment] 2015-06-11 19:35
Ah yes it's a duplicate.

**Comment by erg** [comment] 2015-06-11 23:20
Duplicate. Now someone patch it :8ball: :facepunch: :racehorse: :last_quarter_moon_with_face:

**Closed by erg** 2015-06-11 23:20 UTC
Labels: floats, maths, parser, performance
