### ISSUE TITLE
refresh-all doesn't seem to work.

### ISSUE THREAD

**Issue by rogerlevy** [slavapestov/factor#1459] opened 2015-08-26 02:01 UTC
Hitting F2 or typing in refresh-all doesn't work.  Always have to manually use reload.

**Comment by mrjbq7** [comment] 2015-08-26 02:08
On which OS?

Is there anything different about the mount point that Factor is running from?

**Comment by rogerlevy** [comment] 2015-08-26 02:12
Windows 8.1

Not sure I understand the second question.  It's just in a directory under my user folder in the C: drive

**Comment by rogerlevy** [comment] 2015-08-26 02:15
I did move it from the original install location however, could that have messed it up

**Comment by mrjbq7** [comment] 2015-08-26 02:22
Hmm, I'm not sure. Maybe there is an issue with our file system monitors on Win8.1?

If you run ``"io.monitors" test`` does it report failures?

**Comment by rogerlevy** [comment] 2015-08-26 02:27
Unit Test: { [ ] [ "monitor-test" temp-file make-directory ] }
Unit Test: { [ ] [ "monitor-test" temp-file t <monitor> "m" set ] }
Unit Test: { [ ] [ "monitor-test/a1" temp-file make-directory ] }
Unit Test: { [ ] [ "monitor-test/a2" temp-file make-directory ] }
Unit Test: {
    [ ]
    [
        "monitor-test/a1" temp-file "monitor-test/a2" temp-file
        move-file-into
    ]
}
Unit Test: { [ t ] [ "monitor-test/a2/a1" temp-file exists? ] }
Unit Test: { [ ] [ "monitor-test/a2/a1/a3.txt" temp-file touch-file ] }
Unit Test: { [ t ] [ "monitor-test/a2/a1/a3.txt" temp-file exists? ] }
Unit Test: { [ ] [ "monitor-test/a2/a1/a4.txt" temp-file touch-file ] }
Unit Test: { [ ] [ "monitor-test/a2/a1/a5.txt" temp-file touch-file ] }
Unit Test: { [ ] [ "monitor-test/a2/a1/a4.txt" temp-file delete-file ] }
Unit Test: {
    [ ]
    [
        "monitor-test/a2/a1/a5.txt" temp-file
        "monitor-test/a2/a1/a4.txt" temp-file move-file
    ]
}
Unit Test: { [ t ] [ "monitor-test/a2/a1/a4.txt" temp-file exists? ] }
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: { [ ] [ "monitor-test/xyz" temp-file make-directories ] }
Unit Test: { [ ] [ "monitor-test" temp-file t <monitor> "m" set ] }
Unit Test: { [ ] [ 1 <count-down> "b" set ] }
Unit Test: { [ ] [ 1 <count-down> "c1" set ] }
Unit Test: { [ ] [ 1 <count-down> "c2" set ] }
Unit Test: {
    [ ]
    [
        [
            "b" get count-down [
                "m" get next-change path>> dup print
                flush dup parent-directory
                [ trim-tail-separators "xyz" tail? ] either? not
            ] loop "c1" get count-down [
                "m" get next-change path>> dup print
                flush dup parent-directory
                [ trim-tail-separators "yxy" tail? ] either? not
            ] loop "c2" get count-down
        ] "Monitor test thread" spawn drop
    ]
}
Unit Test: { [ ] [ "b" get await ] }
Unit Test: { [ ] [ "monitor-test/xyz/test.txt" temp-file touch-file ] }
Unit Test: { [ ] [ "c1" get 1 minutes await-timeout ] }
\\?\C:\Users\Roger\AppData\Local\Temp\factorcode.org\Factor\monitor-test\xyz\test.txt
Unit Test: {
    [ ]
    [
        "monitor-test/subdir/blah/yxy" temp-file
        make-directories
    ]
}
Unit Test: {
    [ ]
    [
        "monitor-test/subdir/blah/yxy/test.txt" temp-file
        touch-file
    ]
}
Unit Test: { [ ] [ "c2" get 1 minutes await-timeout ] }
\\?\C:\Users\Roger\AppData\Local\Temp\factorcode.org\Factor\monitor-test\subdir
\\?\C:\Users\Roger\AppData\Local\Temp\factorcode.org\Factor\monitor-test\subdir\blah
\\?\C:\Users\Roger\AppData\Local\Temp\factorcode.org\Factor\monitor-test\subdir\blah\yxy
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: {
    [ ]
    [ [ "" resource-path f <monitor> ] with-monitors dispose ]
}
Unit Test: {
    [ ]
    [ [ "" resource-path t <monitor> ] with-monitors dispose ]
}
Unit Test: { [ ] [ "monitor-timeout-test" temp-file make-directories ] }
Unit Test: { [ ] [ "monitor-timeout-test" temp-file f <monitor> "m" set ] }
Unit Test: { [ ] [ 3 seconds "m" get set-timeout ] }
Must Fail: { [ [ t ] [ "m" get next-change drop ] while ] }
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: { [ ] [ "monitor-timeout-test" temp-file t <monitor> "m" set ] }
Unit Test: { [ ] [ 3 seconds "m" get set-timeout ] }
Must Fail: { [ [ t ] [ "m" get next-change drop ] while ] }
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: {
    [ ]
    [
        <promise> "p" set "monitor-test" temp-file t <monitor>
        "m" set 10 seconds "m" get set-timeout
    ]
}
Unit Test: { [ ] [ 1 seconds sleep ] }
Unit Test: { [ ] [ "m" get dispose ] }
Unit Test: {
    [ t ]
    [ "p" get 10 seconds ?promise-timeout already-disposed? ]
}

**Comment by rogerlevy** [comment] 2015-08-26 02:27
(I don't know if there are any failures there.  Seems not, but I pasted the output just in case.)

**Comment by mrjbq7** [comment] 2015-08-26 02:29
Are you running a recent nightly build?

Looks like no failures. They would report in the UI listener in the error list, or as ``:test-failures`` in the command line.

**Comment by rogerlevy** [comment] 2015-08-26 02:56
no, using 0.97 from the front page

**Comment by mrjbq7** [comment] 2015-08-26 03:59
I'm not aware of any bug we fixed but am curious if the latest nightly build works for you.

@erg thoughts?

**Comment by rogerlevy** [comment] 2015-08-26 06:29
It works now.  I even went back to using 0.97 and that works now too.

**Comment by mrjbq7** [comment] 2015-08-26 16:18
Hmm, so some kind of heisenbug maybe.

The two tests I would try are:

1) Start Factor, make a change to a file, then try refresh-all.

2) Make a change to a file, start Factor, then try refresh-all.

Another different idea, since we use Windows file notify API for watching directories recursively...

3) Start Factor, rename the directory Factor is running in, then try making changes...

Let's keep this open until we find out if its a bug or not!

**Comment by rogerlevy** [comment] 2015-08-26 20:55
I was  having the issue again so I checked on the thread.

I just did the following:

Change a file
Start Factor
refresh-all  (nothing reloaded, but that's correct because i edited the file before starting Factor)
Change a file
refresh-all
File is loaded correctly

However the issue is not happening anymore.  I will try to pay attention to what I'm doing the next time it starts happening again.  

(note that I can't rename the folder while factor.exe is running)

**Comment by jonenst** [comment] 2015-08-27 08:29
> Change a file
Start Factor
refresh-all (nothing reloaded, but that's correct because i edited the file before starting Factor)

This should reload the file. Factor keeps a checksum of the contents of each file. The first time you do refresh-all, all the files checksums are checked. The next times you do refresh-all, only the checksums of the modified files (detected using the io.monitors) are checked to make it faster.

One thing is that you really have to change the contents of the file (add whitespace or whatever) compared to the last time it was compiled and saved to the image, not just save the same contents.

**Comment by rogerlevy** [comment] 2015-09-29 15:07
Every time I test I always make a real change to the contents of the file not just re-save.

I have noticed that refresh-all seems to work once and only once, each new Factor session.

**Comment by mrjbq7** [comment] 2015-09-29 15:17
Once per session per file? Or just once per session?

Would there be any error logs anywhere that might give us some information? Like using the Console.app in Mac OSX?

**Comment by mrjbq7** [comment] 2015-09-29 15:27
(Like a place where writing to stdout shows up)

Also if you start factor and do `threads`, then break refresh-all then do `threads.`, is there any difference ?

**Comment by mrjbq7** [comment] 2015-10-08 23:52
Looks like a problem with running 32-bit windows builds on a 64-bit windows.

**Comment by mrjbq7** [comment] 2015-10-08 23:53
Can reproduce!

**Comment by mrjbq7** [comment] 2015-10-09 00:00
@erg I need your Windows expertise :-)

**Comment by mrjbq7** [comment] 2015-10-09 00:17
Seems like ``refresh-all`` works once, then not again.

**Comment by erg** [comment] 2015-10-10 02:16
I can't reproduce at all. It works for me. win32 on win64 windows 10. I don't think it matters that it's on win64, but I can make a win32 box if necessary. (?)

Can you give me exact steps to reproduce?

**Comment by erg** [comment] 2015-10-10 03:06
I chanted a ``uint ref`` to ``DWORD ref`` to match the win32 api call. This one shouldn't matter, but then I found a ``PLONG`` that was a ``int``, and ``LONG`` is 4 bytes on win32 and 8 bytes on win64.

We should comb through the rest of the code and make sure all of the other usages of ``<ref>`` and ``deref`` match up on all the platform-specific code.

**Comment by mrjbq7** [comment] 2015-10-10 03:40
@erg so it breaks pretty regularly for me.

1) start windows 10 64-bit
2) start factor 32-bit
3) load a vocab, like ``USE: 99-bottles``
4) edit 99-bottles.factor to have something stupid like ``CONSTANT: foo 12``
5) refresh-all (it works)
6) change to ``CONSTANT: foo 14``
7) refresh-all (it is broken)

**Comment by mrjbq7** [comment] 2015-10-10 03:41
It's weird the ``io.monitors`` tests work fine.  Somehow it's not testing this scenario.

**Comment by erg** [comment] 2015-10-10 03:42
I fixed up some more constants. Try now. (I'll try your repro steps now.)

**Comment by mrjbq7** [comment] 2015-10-10 03:42
How to I build 32-bit on windows? I've been using a nightly binary to test with.

I'm such a windows n00b.

**Comment by erg** [comment] 2015-10-10 03:43
Your steps don't show the buggy behavior for me. :8ball: :8ball: :8ball:

**Comment by mrjbq7** [comment] 2015-10-10 03:43
Any way of testing on the old binary?

**Comment by mrjbq7** [comment] 2015-10-10 03:44
Oh man @rogerlevy is going to understand how awesome factor is when his refresh-all works.

**Comment by erg** [comment] 2015-10-10 03:44
You have to use the 32bit shell that installs with visual studio. Mine is called ``VS2015 x86 Native Tools Command Prompt``

**Comment by mrjbq7** [comment] 2015-10-10 03:44
Hmmmm, that sounds difficult.  I'm going to wait for a build from the test machines and try again :-)

**Comment by erg** [comment] 2015-10-10 03:44
The target is:

``%comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" x86``

**Comment by mrjbq7** [comment] 2015-10-10 03:45
(Also, not that difficult, but I'm about to do dinner, so it's convenient to wait).

**Comment by mrjbq7** [comment] 2015-10-10 03:45
We should hack on 0.98 together soon.

**Comment by mrjbq7** [comment] 2015-10-10 03:45
I've got some new application icons from my 99designs contest that look kinda better than our triangle.

**Comment by erg** [comment] 2015-10-10 03:46
Svg? Link? Hack yes! Should chat OOB tho :palm_tree:

**Comment by erg** [comment] 2015-10-10 03:47
Btw, the x86 Native Tools link should be right next to the x64 Tools Link if you installed enough optional packages.

**Comment by mrjbq7** [comment] 2015-10-10 03:51
Okay, I'm building 32-bit from source, let me see how that goes.

Can chat later about other stuff.

**Comment by mrjbq7** [comment] 2015-10-10 04:00
Okay, refresh-all works for me in my 32-bit build.  Let's test the nightly when it finishes running all of its tests and uploads. If that works, @rogerlevy is good-to-go.

**Comment by mrjbq7** [comment] 2015-10-10 04:00
P.S. @erg rocks.

**Comment by erg** [comment] 2015-10-10 04:00
I don't know what would have fixed it except some of the flags? Slightly concerned here!

**Comment by mrjbq7** [comment] 2015-10-10 04:02
Well, my steps always break in my 32-bit nightly download and don't break in my updated @erg patches 32-bit build.

Let me test the nightly later.

**Comment by erg** [comment] 2015-10-10 04:04
What do you think about ctrl-e and ctrl-h not working unless the vocabulary is USE:d ? Another bug?

**Comment by mrjbq7** [comment] 2015-10-10 04:12
you think it should throw a restart like pressing enter?

**Comment by erg** [comment] 2015-10-10 04:14
Yeah, that would be better than doing nothing as it confuses people (me,
roger probably unless his bug was something else).

**Comment by mrjbq7** [comment] 2015-10-10 04:17
i never noticed that, maybe because I always have words in scope.  Are you going to try and fix that or should I?

**Comment by erg** [comment] 2015-10-10 04:22
Do you know how to do it easily? If so go ahead, otherwise I can do it
eventually.

**Comment by mrjbq7** [comment] 2015-10-10 04:23
I'll look at it and see.

**Comment by mrjbq7** [comment] 2015-10-10 05:11
It might be a little complicated to throw the right restart, but I have some code that does something.

Workaround is to hit TAB then pick the one you want then hit Ctrl-E/H.

**Comment by mrjbq7** [comment] 2015-10-10 20:02
@erg still busted.  Can you try downloading the nightly binary and running my steps above to reproduce?

**Comment by mrjbq7** [comment] 2015-10-10 20:02
For some reason the 32-bit build locally works.

**Comment by mrjbq7** [comment] 2015-10-10 20:18
Could the 32-bit builder have some stale state?

**Comment by erg** [comment] 2015-10-10 20:23
Maybe it's the unzipped file permissions? Can you chmod it all to what the
git version has?

On Sat, Oct 10, 2015 at 1:18 PM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment] 2015-10-10 20:23
How do I chmod on Windows?

**Comment by erg** [comment] 2015-10-10 20:25
Actual chmod gets installed with Windows git installer if you install extra
unix command line utils.

Conceptual chmod you would look at file permissions in file explorer etc or
figure out the recursive way to do it in windows. I'm eating lunch or i'd
look

On Sat, Oct 10, 2015 at 1:23 PM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment] 2015-10-10 23:14
``chmod a+r -R factor-32`` 

doesn't help...

**Comment by mrjbq7** [comment] 2015-10-10 23:15
Well, @rogerlevy has a workaround if he builds his own 32-bit maybe?

I think @erg you're on to something with a FFI call somewhere that doesn't use the "correct" type but works on 32 and 64 but not 32-on-64?

**Comment by erg** [comment] 2015-10-13 19:15
The file-change notifications are coming through correctly. It must be some other part of the ``refresh-all`` code.

**Comment by mrjbq7** [comment] 2015-10-13 19:20
The vocabs.refresh.monitor vocab has all the logic which should work if the
file-change notifications are happening properly.

**Comment by erg** [comment] 2015-10-13 19:24
```factor
: parse-action ( action -- changed )
    [ "got action:" write dup . flush ] with-global
    {
        { FILE_ACTION_ADDED [ +add-file+ ] }
        { FILE_ACTION_REMOVED [ +remove-file+ ] }
        { FILE_ACTION_MODIFIED [ +modify-file+ ] }
        { FILE_ACTION_RENAMED_OLD_NAME [ +rename-file+ ] }
        { FILE_ACTION_RENAMED_NEW_NAME [ +rename-file+ ] }
        [ drop +modify-file+ ]
    } case 1array ;

got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
got action:7
got action:3
got action:3
got action:3
got action:3
got action:3
got action:3
```

**Comment by erg** [comment] 2015-10-13 19:28
It's doing two actions for each time I save the file instead of just one.

**Comment by mrjbq7** [comment] 2015-10-13 19:28
Can you make sure the path is correct?

**Comment by erg** [comment] 2015-10-13 19:30
```
path:"io\\monitors\\windows\\windows.factor"
got action:3
path:"io\\monitors\\windows\\windows.factor"
got action:3
```

**Comment by mrjbq7** [comment] 2015-10-13 19:33
Yeah I get that on linux too sometimes, its because our actions aren't
granular enough.

**Comment by erg** [comment] 2015-10-13 19:34
Or are we really adding it twice?

**Comment by mrjbq7** [comment] 2015-10-13 19:37
changed-vocab just adds it to a hashtable I think so multiple times is no
problem.

**Comment by erg** [comment] 2015-10-13 19:40
Oh, probably the way notepad++ saves is causing the two notifications.

**Comment by erg** [comment] 2015-11-02 21:57
This bug was due to ADS (alternative data streams), specifically the ``foo.factor:Zone.Identifier:$DATA`` stream and the way it interacted with our vocabulary system.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa364404(v=vs.85).aspx

Since Windows XP SP2, pathnames in windows are ``file:stream-name:$stream-type``, which means you can actually do ``"resource:core/assocs/assocs.factor::$DATA" utf8 file-contents`` and it works.

You can also hide data (!) like so:

```factor
"Harmless file, lol" "resource:lol.txt" utf8 set-file-contents
"resource:lol.txt" utf8 file-contents print
Harmless file, lol
```

But you can also then do this:

```factor
"3 secret 5 u" "resource:lol.txt:secrets" utf8 set-file-contents

"resource:lol.txt" utf8 file-contents print
Harmless file, lol

"resource:lol.txt:secrets" utf8 file-contents print
3 secret 5 u

"resource:lol.txt" file-info size>> .
18
"resource:lol.txt:secrets" file-info size>> .
12
```

In file explorer it looks like there's just the normal ``lol.txt`` file, no sign of any other streams.

```factor
"resource:lol.txt" file-streams
V{ ~WIN32_FIND_STREAM_DATA~ ~WIN32_FIND_STREAM_DATA~ }

"resource:lol.txt" file-streams [ STREAM_DATA>out ] map .
V{ { "::$DATA" 18 } { ":secrets:$DATA" 12 } }

"resource:lol.txt" alternate-file-streams [ STREAM_DATA>out ] map .
V{ { ":secrets:$DATA" 12 } }
```

Combined with this, the notification for opening a file from zone 3 (the internet) was causing Factor to throw an exception about the vocabulary name. The monitor pump thread used ``ignore-errors`` so nothing printed to console.

```factor
! First step, print monitor thread fatal errors to console
fatal error for monitor root ``resource:extra``: T{ bad-vocab-name { name "lol.omg:Zone.Identifier" } }
```

```factor
! Second step, print a warning instead and continue to let the monitor pump thread live
monitor-loop warning for path ``\\?\c:\factor64\extra\lol.omg:Zone.Identifier``: T{ bad-vocab-name { name "lol.omg:Zone.Identifier" } }
```


The apis to enumerate streams are ``FindFirstStream`` and ``FindNextStream``, and to read/write/delete the ADS you can just use the regular functions in Factor. Vocabularies can't contain ADS because they have the ``:`` which is prohibited by the vocabulary lookup mechanism because of Windows drive letters. We could revisit this limitation in the future but I'm not sure it's a good idea to allow such hidden vocabularies...

I'm really disappointed that I missed out on knowing this awesome feature (ADS) of the Windows file system for so long. Once new binaries are uploaded, ``refresh-all`` and file monitors should work and spam your console with ``:Zone.Identifier`` warnings, but only if you use the .com from the Windows .zip download. (win32 is broken due to deploy sizes)

Let me know if there are any further improvements or anything we can't do with ADS that is worthwhile to implement.

Sorry it took so long to debug this! Good times!!!  :+1:

**Comment by erg** [comment] 2015-11-02 21:59
Fixed by d23aa7e1f1986726c3e01809d4d1980b1a0f4d2e.

**Closed by erg** 2015-11-02 21:59 UTC
Labels: reloading, windows

**Comment by mrjbq7** [comment] 2015-11-02 22:16
I haven't tried it yet but should we not spam the console?

**Comment by erg** [comment] 2015-11-02 22:16
We should spam the console!

ADS awareness month
